# Generated by Django 5.2.10 on 2026-01-17 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelColumnSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('column_type', models.CharField(default='text', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excel Column Schema',
                'verbose_name_plural': 'Excel Column Schemas',
                'ordering': ['column_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Code (first 2 digits removed)')),
                ('full_path', models.CharField(db_index=True, max_length=1000, verbose_name='Full Path')),
                ('has_excel', models.BooleanField(default=False, verbose_name='Has Excel Files')),
                ('level', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Hierarchy Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='voters.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10, verbose_name='Gender')),
                ('source_file', models.CharField(max_length=500, verbose_name='Source Excel File')),
                ('data', models.JSONField(default=dict, verbose_name='Voter Data (All Excel Columns)')),
                ('voter_no', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Voter No (Extracted)')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name (Extracted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='voters_cate_name_828555_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='voters_cate_parent__527a38_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['category', 'gender'], name='voters_vote_categor_8dd589_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['voter_no'], name='voters_vote_voter_n_bdbe60_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['name'], name='voters_vote_name_6c2fef_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['gender'], name='voters_vote_gender_fa9ab0_idx'),
        ),
    ]
