# Generated by Django 5.2.10 on 2026-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='data',
        ),
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='voter',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='voter',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra Data'),
        ),
        migrations.AddField(
            model_name='voter',
            name='father',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='voter',
            name='mother',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mother Name'),
        ),
        migrations.AddField(
            model_name='voter',
            name='profession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='voter',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Voter No'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['father'], name='voters_vote_father_b72b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['mother'], name='voters_vote_mother_da326a_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['profession'], name='voters_vote_profess_e28aac_idx'),
        ),
    ]
