# Generated by Django 5.2.10 on 2026-01-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_remove_voter_data_voter_address_voter_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='search_text',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Combined Search Text'),
        ),
    ]
