# Generated by Django 5.2.10 on 2026-01-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_voter_search_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterStatusAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('dead', 'Dead')], max_length=10, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('dead', 'Dead')], max_length=10, verbose_name='New Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Voter Status Audit',
                'verbose_name_plural': 'Voter Status Audits',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='voter',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('dead', 'Dead')], db_index=True, default='present', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['status'], name='voters_vote_status_2ebbc4_idx'),
        ),
        migrations.AddField(
            model_name='voterstatusaudit',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='voterstatusaudit',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audits', to='voters.voter', verbose_name='Voter'),
        ),
        migrations.AddIndex(
            model_name='voterstatusaudit',
            index=models.Index(fields=['voter', 'changed_at'], name='voters_vote_voter_i_6a53d1_idx'),
        ),
        migrations.AddIndex(
            model_name='voterstatusaudit',
            index=models.Index(fields=['changed_by', 'changed_at'], name='voters_vote_changed_a332c3_idx'),
        ),
        migrations.AddIndex(
            model_name='voterstatusaudit',
            index=models.Index(fields=['new_status'], name='voters_vote_new_sta_193630_idx'),
        ),
    ]
