# Generated by Django 4.2.27 on 2026-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voterstatusaudit_voter_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Voter No'),
        ),
    ]
