# Generated by Django 5.2.10 on 2026-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_alter_voter_dob_alter_voter_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='serial',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Serial'),
        ),
    ]
