# Generated by Django 4.2.27 on 2026-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_add_serial_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelcolumnschema',
            name='column_type',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=100, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='serial',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('dead', 'Dead')], db_index=True, default='present', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Voter No'),
        ),
    ]
